[env]
TERM = "xterm-256color"

[font]
size = 18

  [font.normal]
  family = "Iosevka"
  style = "Extralight"

  [font.bold]
  style = "Bold"

  [font.italic]
  style = "Italic"

  [font.bold_italic]
  style = "Bold Italic"

[window]
option_as_alt = "Both"
dynamic_padding = false
decorations = "buttonless"
startup_mode = "Windowed"
opacity = 0.85

  [window.padding]
  x = 12
  y = 12

[colors.primary]
background = "#161617"
foreground = "#c9c7cd"

# [colors.primary]
# background = '0xf9f5d7'
# foreground = '0x654735'

[colors.cursor]
text = "#c9c7cd"
cursor = "#757581"

[colors.normal]
black = "#27272a"
red = "#f5a191"
green = "#90b99f"
yellow = "#e6b99d"
blue = "#aca1cf"
magenta = "#e29eca"
cyan = "#ea83a5"
white = "#c1c0d4"

## [colors.normal]
## black = '0x654735'
## red = '0xc14a4a'
## green = '0x6c782e'
## yellow = '0xb47109'
## blue = '0x45707a'
## magenta = '0x945e80'
## cyan = '0x4c7a5d'
## white = '0xf2e5bc'

[colors.bright]
black = "#353539"
red = "#ffae9f"
green = "#9dc6ac"
yellow = "#f0c5a9"
blue = "#b9aeda"
magenta = "#ecaad6"
cyan = "#f591b2"
white = "#cac9dd"

## [colors.bright]
## black = '0x654735'
## red = '0xc14a4a'
## green = '0x6c782e'
## yellow = '0xb47109'
## blue = '0x45707a'
## magenta = '0x945e80'
## cyan = '0x4c7a5d'
## white = '0xf2e5bc'
