[env]
TERM = "xterm-256color"

[font]
size = 14

  [font.normal]
  family = "Dank Mono"
  style = "Regular"

  [font.bold]
  style = "Bold"

  [font.italic]
  style = "Italic"

  [font.bold_italic]
  style = "Bold Italic"

[window]
option_as_alt = "Both"
dynamic_padding = false
decorations = "buttonless"
startup_mode = "Windowed"
opacity = 0.85

  [window.padding]
  x = 12
  y = 12

[colors.primary]
background = "#161617"
foreground = "#c9c7cd"

[colors.cursor]
text = "#c9c7cd"
cursor = "#757581"

[colors.normal]
black = "#27272a"
red = "#f5a191"
green = "#90b99f"
yellow = "#e6b99d"
blue = "#aca1cf"
magenta = "#e29eca"
cyan = "#ea83a5"
white = "#c1c0d4"

[colors.bright]
black = "#353539"
red = "#ffae9f"
green = "#9dc6ac"
yellow = "#f0c5a9"
blue = "#b9aeda"
magenta = "#ecaad6"
cyan = "#f591b2"
white = "#cac9dd"

